config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'application#home'

  get 'varnish' => 'varnish#index', as: :varnish
  get 'xml' => 'xml#index', as: :xml
  get 'json' => 'json#index', as: :json
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def home
    render 'home/home'
  end
end

app/controllers/json_controller.rb
# frozen_string_literal: true

require 'open-uri'

class JsonController < ApplicationController
  def index
    @items = JSON.parse(parse_json).sort_by { |item| item['price'].to_f }
  end

  private

  def parse_json
    URI.parse(ENV['JSON_URL']).open.read
  end
end

app/controllers/varnish_controller.rb
# frozen_string_literal: true

class VarnishController < ApplicationController
  def index
    logs = varnish_raw_logs.split("\n").map { |record| record.scan(/".*?"/) }
    @files = top_files(logs)
    @hostnames = top_hostnames(logs)
  end

  private

  def varnish_raw_logs
    File.read(ENV['VARNISH_LOG_PATH'])
  end

  def top_files(logs)
    files = logs.each_with_object(Hash.new(0)) { |e, total| total[e[0]] += 1; }
    files.sort_by { |_key, value| value }.last(5).reverse
  end

  def top_hostnames(logs)
    hostnames = logs.each_with_object(Hash.new(0)) { |e, total| total[hostname_of(e[0])] += 1; }
    hostnames.sort_by { |_key, value| value }.last(5).reverse
  end

  def hostname_of(url)
    url[%r{://.*?/}].gsub(%r{/|:}, '')
  end
end

app/controllers/xml_controller.rb
# frozen_string_literal: true

require 'open-uri'

class XmlController < ApplicationController
  def index
    @items = parse_xml.xpath('//item').sort_by { |item| item.at('price').text.to_f }
  end

  private

  def parse_xml
    Nokogiri::XML(URI.parse(ENV['XML_URL']).open).remove_namespaces!
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/varnish_helper.rb
# frozen_string_literal: true

module VarnishHelper
end

app/views/home/home.html.erb
<div>
  <%= link_to 'varnish', varnish_path %>
  <%= link_to 'xml', xml_path %>
  <%= link_to 'json', json_path %>
</div>

app/views/json/index.html.erb
<ul>
  <% @items.each do |item| %>
    <li>
      <p><b>Title:</b> <%= item['title'] %></p>
      <p><b>Price:</b> <%= item['price'] %></p>
      <p><b>Link:</b> <%= link_to item['full_url'], item['full_url'] %></p>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PowerMedia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/varnish/index.html.erb
<b>Top 5 files:</b>
<ul>
  <% @files.each do |file| %>
    <li>
      <p><%= file[1] %> requests - <%= file[0] %></p>
    </li>
  <% end %>
</ul>

<b>Top 5 hostnames:</b>
<ul>
  <% @hostnames.each do |hostname| %>
    <li>
      <p><%= hostname[1] %> requests - <%= hostname[0] %></p>
    </li>
  <% end %>
</ul>

app/views/xml/index.html.erb
<ul>
  <% @items.each do |item| %>
    <li>
      <p><b>Title:</b> <%= item.try(:at, 'title').try('text') %></p>
      <p><b>Price:</b> <%= item.try(:at, 'price').try('text') %></p>
      <p><b>Link:</b> <%= link_to item.try(:at, 'link').try('text'), item.try(:at, 'link').try('text') %></p>
    </li>
  <% end %>
</ul>